export const USER_LOGIN_REQUEST = 'USER_lOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_lOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_lOGIN_FAIL'
export const USER_LOGIN_RESET = 'USER_lOGIN_RESET'